### ISSUE TITLE
does not work with absolutely positioned parent elements

### ISSUE THREAD

**Issue by StrikerTwo** [kevinmarx/overflowing#1]
Thank you for your plugin. However I discovered a small issue on using it:
I have a parent div with `position:absolute` and `top:80px` and several child elements that I want to show in a dropdown menu if they overflow the parent div.
Since you compare `element.height + element.top` with `parent.height + parent.top` and `parent.top` is 80 and `element.top` is 0, they will not be marked as overflowing. I just removed parent.top from the equation and it works.
Is there a particular reason for including the parent's top in the calculation?

**Comment by kevinmarx** [comment]
Thank you for pointing this out, the reason we need to use the parent's top and left positioning is for static or inline positioned elements. I have fixed the issue with absolute and fixed positioned parent elements in the latest release.
